[package]
name = "lucie-text"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
lucie-common.workspace = true
lucie-style.workspace = true
parking_lot.workspace = true
rapidhash.workspace = true
smallvec.workspace = true
log.workspace = true
either = "1.15"

parley = { git = "https://github.com/pykeio/parley.git", rev = "97f9a9cc5247fe3365429fadc343cc9d5f57d247", default-features = false, features = [ "std", "system" ] }
skrifa = { version = "0.42.0", default-features = false, features = [ "std", "autohint_shaping" ] }
read-fonts = { version = "0.39", default-features = false }
linebender_resource_handle = "0.1.1"
tiny-skia = { version = "0.12", default-features = false, features = [ "std", "simd" ] }

[dev-dependencies]
tiny-skia = { version = "0.12", default-features = false, features = [ "std", "simd", "png-format" ] }
