[workspace]
resolver = "2"
members = [
	"crates/lucie-common",
    "crates/lucie-macros",
	"crates/lucie-style",
	"crates/lucie-text",
    "crates/lucie",
    "crates/gpui_tokio",
    "crates/media",
    "crates/reqwest_client",
]
default-members = ["crates/lucie"]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.88"
license = "Apache-2.0"
homepage = "https://lucie.pyke.io/"
repository = "https://github.com/pykeio/lucie"
authors = ["Carson M. <carson@pyke.io>"]

[workspace.dependencies]

#
# Workspace member crates
#

lucie-common = { path = "crates/lucie-common" }
lucie-macros = { path = "crates/lucie-macros" }
lucie-style = { path = "crates/lucie-style" }
lucie-text = { path = "crates/lucie-text" }
lucie = { path = "crates/lucie", default-features = false }
gpui_tokio = { path = "crates/gpui_tokio" }
media = { path = "crates/media" }
reqwest_client = { path = "crates/reqwest_client" }

#
# External crates
#

anyhow = "1.0.86"
blade-graphics = { version = "0.7.0" }
blade-macros = { version = "0.3.0" }
blade-util = { version = "0.3.0" }
bytes = "1.0"
cocoa = "=0.26.0"
cocoa-foundation = "=0.2.0"
core-foundation = "=0.10.0"
core-foundation-sys = "0.8.6"
core-video = { version = "0.4.3", features = ["metal"] }
derive_more = "0.99.17"
fastrand = "2.4.1"
futures-core = { version = "0.3", default-features = false, features = [ "std" ] }
futures-util = { version = "0.3", default-features = false, features = [ "std" ] }
http = "1.1"
http-body = "1.0"
image = { version = "0.25.1", default-features = false, features = [ "gif", "jpeg", "png", "webp" ] }
mach2 = "0.5"
metal = "0.29"
naga = { version = "25.0", features = ["wgsl-in"] }
objc = "0.2"
objc2-foundation = { version = "=0.3.1", default-features = false, features = [
    "NSArray",
    "NSAttributedString",
    "NSBundle",
    "NSCoder",
    "NSData",
    "NSDate",
    "NSDictionary",
    "NSEnumerator",
    "NSError",
    "NSGeometry",
    "NSNotification",
    "NSNull",
    "NSObjCRuntime",
    "NSObject",
    "NSProcessInfo",
    "NSRange",
    "NSRunLoop",
    "NSString",
    "NSURL",
    "NSUndoManager",
    "NSValue",
    "objc2-core-foundation",
    "std"
] }
parking_lot = "0.12.1"
rapidhash = "4.1"
smallvec = { version = "1.6", features = [ "union", "const_new", "const_generics" ] }
tokio = { version = "1.48", default-features = false }
tokio-stream = { version = "0.1", default-features = false }
tracing = { version = "0.1", default-features = false, features = [ "std" ] }
windows-core = "0.62"

[workspace.dependencies.windows]
version = "0.62"
features = [
    "System_Threading",
    "UI_ViewManagement",
    "Wdk_System_SystemServices",
    "Win32_Globalization",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_DirectComposition",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Imaging",
    "Win32_Graphics_Hlsl",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_DataExchange",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_System_Performance",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_Variant",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_Ime",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_UI_WindowsAndMessaging",
]

[patch.crates-io]
calloop = { git = "https://github.com/zed-industries/calloop" }

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
debug = "none"
lto = "fat"
codegen-units = 1

[workspace.lints.clippy]
incompatible_msrv = "deny"
declare_interior_mutable_const = "deny"
redundant_clone = "deny"
disallowed_methods = "deny"
type_complexity = "allow"
too_many_arguments = "allow"
large_enum_variant = "allow"
