[files]
ignore-files = true
ignore-hidden = false
extend-exclude = [
    ".git/",

    # Windows likes its abbreviations.
    "crates/lucie/src/platform/windows/directx_renderer.rs",
    "crates/lucie/src/platform/windows/events.rs",
    "crates/lucie/src/platform/windows/direct_write.rs",
    "crates/lucie/src/platform/windows/window.rs",

    # macOS APIs
    "crates/lucie/src/platform/mac/dispatcher.rs",
]

[default]
extend-ignore-re = [
    # macOS version
    "Big Sur",
    # Stripped version of reserved keyword `type`
    "typ",
]
check-filename = true
