[package]
name = "lucie-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true
doctest = true

[dependencies]
proc-macro2 = "1.0.93"
quote = "1.0.9"
syn = { version = "2.0", features = [ "full", "extra-traits", "visit-mut" ] }

[dev-dependencies]
lucie = { workspace = true }
