[package]
name = "lucie-style"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
lucie-common.workspace = true
lucie-macros.workspace = true
smallvec.workspace = true
