[package]
name = "reqwest_client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[features]
test-support = []

[lib]
path = "src/reqwest_client.rs"
doctest = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
lucie = { workspace = true, default-features = false }
tracing.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
tokio-stream = { workspace = true }
tokio-util = { version = "0.7", features = [ "io" ] }
reqwest = { version = "0.13", features = [ "stream" ] }
http.workspace = true
http-body.workspace = true

[dev-dependencies]
lucie.workspace = true
