name: Test
on:
  pull_request:
  push:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v6
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Run tests
      run: |
        cargo test -p gpui --features test-support --lib
